### ISSUE TITLE
role service

### ISSUE THREAD

**Issue by Hekapo** [itis-11013/national-bank-ru#5]
https://github.com/itis-11013/national-bank-ru/blob/749a4fb52f74f76da114b0d36eac920407aa615d/src/main/java/ru/itis/nationalbankru/services/role/RoleService.java#L6

**Comment by Hekapo** [comment]
зачем тут JpaRepo?

**Comment by escalopa** [comment]
Later on I will create functions in this repo to get all users with a specific role for example

**Comment by Hekapo** [comment]
@escalopa rename RoleService to RoleRepository

**Comment by Hekapo** [comment]
and move to repo package

**Comment by escalopa** [comment]
done
